#!/bin/bash

mkdir -p roboresources/pics roboresources/caps roboresources/thumbs 2>/dev/null

patt=".jpg"
if [[ -n "$2" ]]
then
  patt=$2
fi
ppic=$1

## strip suffix
base=`echo $ppic | sed "s/$patt//"`
echo "patt: "$patt
echo "ppic: "$ppic
echo "base: "$base
# strip all to underscore if exists
pic=`echo $base | perl -ne 's/^.*_//; print'`
echo now_$base

mv $ppic roboresources/pics 2>/dev/null
echo "<h1>$base</h1>" > $base.htm
#
stuff=`echo '<img src="_ROBOPATH_roboresources/pics/'$ppic'" alt="'$ppic'"/>'`
echo $stuff >> $base.htm
#
if test -f "$base.cap"; then
    cat $base.cap >> $base.htm
    mv $base.cap roboresources/caps
fi

picSlides

