#!/bin/bash

cwd=`pwd`

for ddir in `find . -type d`
	do
	  dir=${ddir#*.}
  	  dir=$cwd/${dir#/}
		test=`basename $dir`
		if [[ "$test" != ""  &&  "$test" != "slideshow" &&  "$test" != "archive"   &&   "$test" != "pics"   &&   "$test" != "thumbs" && !"$test" =~ "svn" ]] ; then
		~/bin/mmkord $dir
		fi
	done

