#!/bin/bash

pwd=`pwd`
sudo rm -f /tmp/ddelme*
sudo chmod -R 777 $pwd 

mkdir -p roboresources/slideshow 2>/dev/null
rm roboresources/slideshow/*
mkdir -p roboresources/pics 2>/dev/null
mkdir roboresources/thumbs 2>/dev/null

for file in `ls  | egrep '(jpg|png|gif)'`
do
ext="${file##*.}"
base=${file%%.*}
ln -s $pwd/$file roboresources/pics/`basename $file`
done
ln -s $pwd/$file roboresources/pics/index.$ext 


for file in `ls  | egrep '(jpg|png|gif)'`
do
ln -s $pwd/$file roboresources/slideshow/`basename $file`
done

picthumbs
rm -rf thumbs

cd ..
fragfix
