#!/usr/bin/perl

use Cwd;
use File::Basename;
use MIME::Types qw(by_suffix by_mediatype import_mime_types);

($wherePath = shift) =~ s://:/:g; 
if($wherePath eq '.')
{
  $wherePath = getcwd;
}

($whereUrl = $wherePath) =~ s:^.*fragments/::;
($whereUrl = $whereUrl) =~ s:^.*fragments::;
$whereUrl .= '/';
$wherePath .= '/';
$whereUrl='' if $whereUrl eq '/';
$whereUrl = '?robopage=' . $whereUrl;

opendir(DIR, $wherePath);
@files = readdir(DIR);
closedir(DIR);

%filehash;
foreach $file (@files)
{
        next if $file =~ /^\./;
        next if $file =~ /roboresources/;
        next if $file =~ /dirlinks/;
        next if $file =~ /\.cap/;

        ##print "file: $file \n";
        ($path = $whereUrl.$file) =~ s://:/:g;
        $filehash{$path} = $file; 
}

my $href='';
my $label='';


foreach $k (sort(keys %filehash)) 
{
        next if basename($filehash{$k}) =~ /roboresources/;
        $label = $filehash{$k};

        ($k = $k) =~ s:fragments/::;

        $base = basename($k);
        ($suffix = $base) =~ s/^.*\.//;
        my $dalink, $indexlink;


   	    $dalink = "$k".'::'.$label. "\n";
        if(! ($k =~ /index/))
        {
	         print $dalink;
        }else{
           $indexlink = $dalink;
        }
}
print $indexlink, "\n";

